WebApplication2/Models/ErrorViewModel.cs
namespace WebApplication2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication2/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication2.Models
{
    public class LoginViewModel
    {
        [Required]
        [Display(Name = "Логин")]
        public string UserName { get; set; }

        [Required]
        [UIHint("password")]
        [Display(Name = "Пароль")]
        public string Password { get; set; }

        [Display(Name = "Запомнить меня?")]
        public bool RememberMe { get; set; }
    }
}

WebApplication2/Models/ViewComponents/SidebarViewComponents.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication2.Domain;

namespace WebApplication2.Models.ViewComponents
{
    public class SidebarViewComponent : ViewComponent
    {
        private readonly DataManager dataManager;

        public SidebarViewComponent(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public Task<IViewComponentResult> InvokeAsync()
        {
            return Task.FromResult((IViewComponentResult)View("Default", dataManager.ServiceItems.GetServiceItems()));
        }
    }
}

WebApplication2/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication2.Domain;

namespace WebApplication2.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        private readonly DataManager dataManager;

        public HomeController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }
        [Route("{area}")]
        public IActionResult Index()
        {
            return View(dataManager.ServiceItems.GetServiceItems());
        }
    }
}

WebApplication2/Areas/Admin/Controllers/ServiceItemsController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication2.Domain.Entities;
using WebApplication2.Domain;
using WebApplication2.Service;

namespace WebApplication2.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ServiceItemsController : Controller
    {
        private readonly DataManager dataManager;
        private readonly IWebHostEnvironment hostingEnvironment;
        public ServiceItemsController(DataManager dataManager, IWebHostEnvironment hostingEnvironment)
        {
            this.dataManager = dataManager;
            this.hostingEnvironment = hostingEnvironment;
        }
        [Route("{area}/{controller}/{action}")]
        public IActionResult Edit(Guid id)
        {
            var entity = id == default ? new ServiceItem() : dataManager.ServiceItems.GetServiceItemById(id);
            return View(entity);
        }
        [HttpPost]
        [Route("{area}/{controller}/{action}")]
        public IActionResult Edit(ServiceItem model, IFormFile titleImageFile)
        {
            if (ModelState.IsValid)
            {
                if (titleImageFile != null)
                {
                    model.TitleImagePath = titleImageFile.FileName;
                    using (var stream = new FileStream(Path.Combine(hostingEnvironment.WebRootPath, "images/", titleImageFile.FileName), FileMode.Create))
                    {
                        titleImageFile.CopyTo(stream);
                    }
                }
                dataManager.ServiceItems.SaveServiceItem(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }

        [HttpPost]
        [Route("{area}/{controller}/{action}")]
        public IActionResult Delete(Guid id)
        {
            dataManager.ServiceItems.DeleteServiceItem(id);
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
        }
    }
}

WebApplication2/Areas/Admin/Controllers/TextFieldsController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication2.Domain.Entities;
using WebApplication2.Domain;
using WebApplication2.Service;

namespace WebApplication2.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TextFieldsController : Controller
    {
        private readonly DataManager dataManager;
        public TextFieldsController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }
        [Route("{area}/{controller}/{action}")]
        public IActionResult Edit(string codeWord)
        {
            var entity = dataManager.TextFields.GetTextFieldByCodeWord(codeWord);
            return View(entity);
        }

        [HttpPost]
        [Route("{area}/{controller}/{action}")]
        public IActionResult Edit(TextField model)
        {
            if (ModelState.IsValid)
            {
                dataManager.TextFields.SaveTextField(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }
    }
}

WebApplication2/Controllers/AccountController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    [Authorize]
    public class AccountController : Controller
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;
        public AccountController(UserManager<IdentityUser> userMgr, SignInManager<IdentityUser> signinMgr)
        {
            userManager = userMgr;
            signInManager = signinMgr;
        }

        [AllowAnonymous]
        public IActionResult Login(string returnUrl)
        {
            ViewBag.returnUrl = returnUrl;
            return View(new LoginViewModel());
        }
        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginViewModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                IdentityUser user = await userManager.FindByNameAsync(model.UserName);
                if (user != null)
                {
                    await signInManager.SignOutAsync();
                    Microsoft.AspNetCore.Identity.SignInResult result = await signInManager.PasswordSignInAsync(user, model.Password, model.RememberMe, false);
                    if (result.Succeeded)
                    {
                        return Redirect(returnUrl ?? "/");
                    }
                }
                ModelState.AddModelError(nameof(LoginViewModel.UserName), "Неверный логин или пароль");
            }
            return View(model);
        }

        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

WebApplication2/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplication2.Domain;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class HomeController : Controller
    {
        private readonly DataManager dataManager;
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger, DataManager dataManager)
        {
            _logger = logger;
            this.dataManager = dataManager;
        }
        public IActionResult Index()
        {
            return View(dataManager.TextFields.GetTextFieldByCodeWord("PageIndex"));
        }

        public IActionResult Contacts()
        {
            return View(dataManager.TextFields.GetTextFieldByCodeWord("PageContacts"));
        }
    }
}

WebApplication2/Controllers/ServicesController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication2.Domain;

namespace WebApplication2.Controllers
{
    public class ServicesController : Controller
    {
        private readonly DataManager dataManager;

        public ServicesController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index(Guid id)
        {
            if (id != default)
            {
                return View("Show", dataManager.ServiceItems.GetServiceItemById(id));
            }

            ViewBag.TextField = dataManager.TextFields.GetTextFieldByCodeWord("PageNews");
            return View(dataManager.ServiceItems.GetServiceItems());
        }
    }
}

WebApplication2/Areas/Admin/Views/Home/Index.cshtml
@model IQueryable<ServiceItem>
@{
    string strTitle = "Панель администратора";
    ViewBag.Title = strTitle;
}

<div>
    <h2>@strTitle</h2>
    <div>
        <h3>Наши услуги</h3>
        <div class="div-box">
            <a asp-area="Admin" asp-controller="ServiceItems" asp-action="Edit" asp-route-id="">Добавить новость</a>
        </div>
        @if (Model.Any())
        {
            <div>
                @foreach (ServiceItem entity in Model)
                {
                    <div>
                        <a asp-area="Admin" asp-controller="ServiceItems" asp-action="Edit" asp-route-id="@entity.Id">редактировать</a>
                        |
                        <form style="display: inline-block;" id="form-@entity.Id" asp-area="Admin" asp-controller="ServiceItems" asp-action="Delete" method="post">
                            <input type="hidden" name="id" value="@entity.Id">
                            <a href="#" onclick="document.getElementById('form-@entity.Id').submit();">удалить</a>
                        </form>
                        |
                        <a asp-area="" asp-controller="Services" asp-action="Index" asp-route-id="@entity.Id">
                            @($"{entity.Title}")
                        </a>
                    </div>
                }
            </div>
        }
    </div>
    <div class="div-box">
        <h3>Редактировать страницы сайта</h3>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageIndex">Главная</a>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageNews">Новости</a>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageContacts">Контакты</a>
    </div>
    <div class="div-box">
        <form asp-area="Admin" asp-controller="Account" asp-action="Logout" method="post">
            <input type="submit" value="Выйти" />
        </form>
    </div>
</div>

WebApplication2/Areas/Admin/Views/ServiceItems/Edit.cshtml
@model ServiceItem
@{
    string strTitle = "Редактировать запись";
    ViewBag.Title = strTitle;
}

<script src="~/js/ckeditor/ckeditor.js"></script>
<script src="~/js/ckeditor/translations/ru.js"></script>

<div>
    <h2>@strTitle</h2>
    <div>
        <form asp-area="Admin" asp-controller="ServiceItems" asp-action="Edit" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="DateAdded" />
            <input type="hidden" asp-for="TitleImagePath" />

            <div asp-validation-summary="All"></div>
            <div class="div-box">
                <label asp-for="Title"></label>
                <input asp-for="Title" />
                <span asp-validation-for="Title"></span>
            </div>
            <div class="div-box">
                <label asp-for="Text"></label>
                <textarea asp-for="Text" id="editor"></textarea>
                <span asp-validation-for="Text"></span>
            </div>
            <div class="div-box">
                <label asp-for="TitleImagePath"></label>
                <input type="file" name="titleImageFile" id="titleImageFile" />
                <div>
                    <img class="img-block" src="~/images/@Model.TitleImagePath" />
                </div>
            </div>
            <div class="div-box">
                <label asp-for="MetaTitle"></label>
                <input asp-for="MetaTitle" />
                <span asp-validation-for="MetaTitle"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaDescription"></label>
                <input asp-for="MetaDescription" />
                <span asp-validation-for="MetaDescription"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaKeywords"></label>
                <input asp-for="MetaKeywords" />
                <span asp-validation-for="MetaKeywords"></span>
            </div>
            <input type="submit" value="Сохранить" />
        </form>
    </div>
</div>



<script>
    ClassicEditor
        .create(document.querySelector('#editor'),
            { language: 'ru' })
        .catch(error => {
            console.error(error);
        });
</script>

WebApplication2/Areas/Admin/Views/TextFields/Edit.cshtml
@model TextField
@{
    string strTitle = "Редактировать запись";
    ViewBag.Title = strTitle;
}
<script src="~/js/ckeditor/ckeditor.js"></script>
<script src="~/js/ckeditor/translations/ru.js"></script>

<div>
    <h2>@strTitle</h2>
    <div>
        <form asp-area="Admin" asp-controller="TextFields" asp-action="Edit" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="DateAdded" />
            <input type="hidden" asp-for="CodeWord" />

            <div asp-validation-summary="All"></div>
            <div class="div-box">
                <label asp-for="Title"></label>
                <input asp-for="Title" />
                <span asp-validation-for="Title"></span>
            </div>
            <div class="div-box">
                <label asp-for="Text"></label>
                <textarea asp-for="Text" id="editor"></textarea>
                <span asp-validation-for="Text"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaTitle"></label>
                <input asp-for="MetaTitle" />
                <span asp-validation-for="MetaTitle"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaDescription"></label>
                <input asp-for="MetaDescription" />
                <span asp-validation-for="MetaDescription"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaKeywords"></label>
                <input asp-for="MetaKeywords" />
                <span asp-validation-for="MetaKeywords"></span>
            </div>
            <input type="submit" value="Сохранить" />
        </form>
    </div>
</div>
<script>
    ClassicEditor
        .create(document.querySelector('#editor'),
            { language: 'ru' })
        .catch(error => {
            console.error(error);
        });
</script>

WebApplication2/Views/Home/Contacts.cshtml
@model TextField
@{
    ViewBag.Title = Model.MetaTitle;
    ViewBag.Description = Model.MetaDescription;
    ViewBag.Keywords = Model.MetaKeywords;
}

<div>
    @Html.Raw(Model.Text)
</div>

WebApplication2/Views/Home/Index.cshtml
@model TextField
@{
    ViewBag.Title = Model.MetaTitle;
    ViewBag.Description = Model.MetaDescription;
    ViewBag.Keywords = Model.MetaKeywords;
}

<div>
    @Html.Raw(Model.Text)
</div>

WebApplication2/Views/Services/Index.cshtml
@model IQueryable<ServiceItem>
@{
    TextField textField = ViewBag.TextField;

    ViewBag.Title = textField.MetaTitle;
    ViewBag.Description = textField.MetaDescription;
    ViewBag.Keywords = textField.MetaKeywords;
}

<div>
    @if (Model.Any())
    {
        <ul class="big-image-list">
            @foreach (ServiceItem entity in Model)
            {
                <li>
                    <a asp-area="" asp-controller="Services" asp-action="Index" asp-route-id="@entity.Id">
                        <img src="~/images/@entity.TitleImagePath" alt="" class="left" />
                    </a>
                    <h4>@entity.Title</h4>
                    <p>@entity.DateAdded</p>
                </li>
            }
        </ul>
    }
</div>

WebApplication2/Views/Services/Show.cshtml
@model ServiceItem
@{
    ViewBag.Title = Model.MetaTitle;
    ViewBag.Description = Model.MetaDescription;
    ViewBag.Keywords = Model.MetaKeywords;
}

<div>
    <h2>
        @Model.Title
    </h2>
    <h1>
        @Model.DateAdded
    </h1>
    <div>
        <img class="img-block" src="~/images/@Model.TitleImagePath" />
    </div>
</div>
<div>
    @Html.Raw(Model.Text)
</div>

WebApplication2/Views/Shared/CssPartial.cshtml
<link rel="stylesheet" href="~/css/main.min.css" asp-append-version="true"/>

WebApplication2/Views/Shared/FooterPartial.cshtml
<!-- Footer -->
<div id="footer-wrapper">
	<div class="container">
		<div class="row">
			<div class="col-8 col-12-medium">

				<section>
					<h2>Текст ради текста</h2>
					<div>
						<div class="row">
							<div class="col-3 col-6-medium col-12-small">
								<ul class="link-list">
									<li><a href="#">Sed neque nisi consequat</a></li>
								</ul>
							</div>
							<div class="col-3 col-6-medium col-12-small">
								<ul class="link-list">
									<li><a href="#">Quis accumsan lorem</a></li>
								</ul>
							</div>
							<div class="col-3 col-6-medium col-12-small">
								<ul class="link-list">
									<li><a href="#">Sed neque nisi consequat</a></li>
								</ul>
							</div>
							<div class="col-3 col-6-medium col-12-small">
								<ul class="link-list">
									<li><a href="#">Quis accumsan lorem</a></li>
								</ul>
							</div>
						</div>
					</div>
				</section>

			</div>
			<div class="col-4 col-12-medium">

				<section>
					<h2>Какое-то описание</h2>
					<p>
						Duis neque nisi, dapibus sed mattis quis, rutrum accumsan sed.
						Suspendisse eu varius nibh. Suspendisse vitae magna eget odio amet
						mollis justo facilisis quis. Sed sagittis mauris amet tellus gravida
						lorem ipsum dolor sit blandit.
					</p>
					<footer class="controls">
						<a href="#" class="button">Дизайн кнопки</a>
					</footer>
				</section>

			</div>
		</div>
		<div class="row">
			<div class="col-12">

				<div id="copyright">
					&copy;Студент. Свободный доступ | Design: <a href="http://html5up.net">HTML5 UP</a>
				</div>

			</div>
		</div>
	</div>
</div>

WebApplication2/Views/Shared/HeaderPartial.cshtml
<!-- Header -->
<div id="header-wrapper">
	<div class="container">
		<div class="row">
			<div class="col-12">

				<header id="header">
					<h1><a href="/" id="logo">@Config.CompanyName</a></h1>
					<nav id="nav">
						<a asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
						<a asp-area="" asp-controller="Services" asp-action="Index" asp-route-id="">Новости</a>
						<a asp-area="" asp-controller="Home" asp-action="Contacts">Контакты</a>
					</nav>
				</header>
			</div>
		</div>
	</div>
</div>

WebApplication2/Views/Shared/MetatagPartial.cshtml
@using WebApplication2.Service
@if(ViewBag.Title != null)
{
    <title>@ViewBag.Title</title>
}
else
{
    <title>@Config.CompanyName</title>
}
@if (ViewBag.Description != null)
{
    <meta name="description" content="@ViewBag.Description" />
}
@if (ViewBag.Keywords != null)
{
    <meta name="keywords" content="@ViewBag.Keywords" />
}

<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />

WebApplication2/Views/Shared/ScriptsPartial.cshtml
@*<script src="assets/js/jquery.min.js"></script>
<script src="assets/js/browser.min.js"></script>
<script src="assets/js/breakpoints.min.js"></script>
<script src="assets/js/util.js"></script>
<script src="assets/js/main.js"></script>*@
<script src ="~/js/scripts.min.js" asp-append-version="true"></script>

WebApplication2/Views/Shared/SidebarPartial.cshtml
<div>
<h2>Какие-то важные ссылки</h2>
<div>
			<ul class="link-list">
				<li><a href="#">Sed neque nisi consequat</a></li>
				<li><a href="#">Quis accumsan lorem</a></li>
				<li><a href="#">Sed neque nisi consequat</a></li>
				<li><a href="#">Quis accumsan lorem</a></li>
			</ul>
</div>
</div>

WebApplication2/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html>
<head>
@await Html.PartialAsync("MetatagPartial")
@await Html.PartialAsync("CssPartial")
	
</head>
<body>
	<div id="page-wrapper">
		@await Html.PartialAsync("HeaderPartial")
		

		<!-- Main -->
		<div id="main">
			<div class="container">
				<div class="row main-row">
					<div class="col-8 col-12-medium">
						@RenderBody()
					</div>
					@await Html.PartialAsync("SidebarPartial")
				</div>
			</div>
		</div>

		@await Html.PartialAsync("FooterPartial")

	</div>

	@await Html.PartialAsync("ScriptsPartial")

</body>
</html>